### ISSUE TITLE
[PHP 7.3] [Doctrine]  Warning: "continue" targeting switch is equivalent to "break".

### ISSUE THREAD

**Issue by guillaumemaka** [doctrine/DoctrineORMModule#579]
Recently updated to PHP 7.3 I got this warning:

Using project autoloader based on current working directory
PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /code/ebos/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2718

See doctrine/doctrine2#7402
Fixed doctrine/doctrine2#7325

Do you plan to update the dependencies ?

**Comment by VascoRatoGFI** [comment]
I found a workaround, checking the file where the warning comes from, UnitOfWork.php, we find the following structure:

```php
foreach ($class->associationMappings as $field => $assoc) {

    //some logic

    switch (true) {
        case($assoc['type'] & ClassMetadata::TO_ONE):

            //some more logic

            if(isset($data[$field]) && is_object($data[$field]) && isset($this->entityStates[spl_object_hash($data[$field])])) {
                
                //do stuff
                
                continue;  // <---- Statement that gives the error
            }

            //some more code
    
    } //end of switch
} //end of foreach
```

Since the switch statement is the last statement on the foreach loop, then using `break`, `continue` and `continue 2` will all have the same behavior. 

Therefore, you are safe to edit the file and replace `continue` with either `break` or `continue 2` to prevent the warning message. I did so and found no issues.

**Comment by Fever905** [comment]
Just downloaded composer for the first time, and trying to install the php-firebase admin panel using:

`composer require kreait/firebase-php ^4.35`

Resulting output:
`Using version ^4.35 for kreait/firebase-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, deleting ./composer.json.


  [ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?


require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
`

**Comment by ankurweb** [comment]
Message: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

**Comment by michalbundyra** [comment]
@ankurweb what version are you using? Check `composer show`.
Any reference? I bet it has been already solved... Try `composer update`.

**Comment by Shonen17** [comment]
> EDIT: This issue has been fixed, running `composer update` will solve the problem.
> 
> I found a workaround, checking the file where the warning comes from, UnitOfWork.php, we find the following structure:
> 
> ```
> foreach ($class->associationMappings as $field => $assoc) {
> 
>     //some logic
> 
>     switch (true) {
>         case($assoc['type'] & ClassMetadata::TO_ONE):
> 
>             //some more logic
> 
>             if(isset($data[$field]) && is_object($data[$field]) && isset($this->entityStates[spl_object_hash($data[$field])])) {
>                 
>                 //do stuff
>                 
>                 continue;  // <---- Statement that gives the error
>             }
> 
>             //some more code
>     
>     } //end of switch
> } //end of foreach
> ```
> 
> Since the switch statement is the last statement on the foreach loop, then using `break`, `continue` and `continue 2` will all have the same behavior.
> 
> Therefore, you are safe to edit the file and replace `continue` with either `break` or `continue 2` to prevent the warning message. I did so and found no issues.

This is not fixed at all.
I have PHP 7.3, and the last version of Prestashop (downloaded and installed today, 29/01/2020, Prestashop 1.7.6.3), and I have this exact same error.
I can't run composer because I don't have a SSH access, but your solution worked.

How can Prestashop be this buggy...

**Comment by s001dxp** [comment]
This is not fixed!! I'm running the latest version with php 7.3 and am getting the same error

**Comment by TomHAnderson** [comment]
Rather than say "the latest version" please tell us the exact version.  A dump of `composer show` would be fine.

**Comment by Notmarrco** [comment]
I had the same error with composer 1.5.x.

For me updating composer worked.
```sh
$ composer --version
Composer 1.9.0 2019-08-02 20:55:32
```

**Comment by pbrisson** [comment]
Confirmed what @Notmarrco said above...

I was using composer 1.2.2

`Composer version 1.2.2 2016-11-03 17:43:15`

Updated to 1.10.5 and `composer update` became possible again...

`Composer version 1.10.5 2020-04-10 11:44:22`

**Comment by fcocosta31** [comment]
Try this:
Edit the line "beberlei/DoctrineExtensions" in your composer.json and composer.lock
Put then in lower case: "beberlei/doctrineextensions" and save
Finally run composer update --no-plugins --no-scripts

**Comment by 7ochem** [comment]
...

**Comment by TomHAnderson** [comment]
@7ochem Your post doesn't relate to this module and indeed this module is for Laminas.

**Comment by 7ochem** [comment]
> @7ochem Your post doesn't relate to this module and indeed this module is for Laminas.

I see now, sorry for that. Placed my comment on the main issue (as the original issue occurred there): doctrine/orm#7402

**Comment by RicardoBer** [comment]
replace
`continue;`
with
`continue 1;`

**Comment by danirupe** [comment]
In my case replace
`continue;`
with
`continue 2;`
